name: legacy_context_menu
description: "A simple, extensible context menu."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0-196.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
