name: legacy_context_menu
description: "A simple, extensible context menu for Flutter that supports nested and collapsible submenus."
version: 2.1.2
homepage: https://github.com/barneysspeedshop/legacy_context_menu
repository: https://github.com/barneysspeedshop/legacy_context_menu
issue_tracker: https://github.com/barneysspeedshop/legacy_context_menu/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


screenshots:
  - description: 'Legacy Context Menu - screenshot 1'
    path: assets/example.png